name: "Generate DB (partial)"
description: "Run a subset of the `make db` target implemented in `holdem/unittests/regenerate_opening_book.cpp`"
inputs:
  cpu_threads_expected:
    description: "e.g. '3'"
    required: true
  regenerate_opening_book_modes:
    description: "e.g. '16 17 18'"
    required: true
  rotation_suffix:
    description: "e.g. '1of3'"
    required: true
runs:
  using: "composite" # https://www.jameskerr.blog/posts/sharing-steps-in-github-action-workflows/

  steps:
  - name: "We already have the executable, so let's just use it rather than: `cd holdem && make db && echo … > ../holdemdb.ini` etc."
    uses: actions/download-artifact@v5
    with:
      name: make-db-requirements
  - name: Assert thread count
    shell: sh
    env:
      HARDCODE_EXPECTED_THREADS: ${{ inputs.cpu_threads_expected }}
    run: |
      sh n_threads_minus_1.sh "$HARDCODE_EXPECTED_THREADS" || exit 78 # EX_CONFIG
      mkdir -vp "$(cat holdemdb.ini)"
  - name: "Generate DB ${{ inputs.rotation_suffix }}"
    shell: sh
    # `HOLDEMDB_PATH: /tmp/opening_book/.../` not needed, we're using holdemdb.ini instead
    env:
      THREAD_COUNT: ${{ inputs.cpu_threads_expected }}
      THREAD_STRIPES: ${{ inputs.regenerate_opening_book_modes }}
    run: echo $THREAD_STRIPES | tr ' ' "\n" | xargs -P "$THREAD_COUNT" -n 1 regenerate_opening_book

  - name: Upload opening book zip
    uses: actions/upload-artifact@v4
    with:
      name: opening_book-${{ inputs.rotation_suffix }}
      path: /tmp/opening_book
      # include-hidden-files: false by default
      if-no-files-found: error
      overwrite: true
      compression-level: 0
      retention-days: 1
