name: Generate Projct Documentation

on:
  workflow_dispatch:

jobs:
  latex_make:
    name: 'Build (see holdem/doc/report)'
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 7
    steps:
    - uses: actions/checkout@v5
    - name: make
      run: cd holdem/doc/report && make

    - name: Upload ece499rpt.pdf
      uses: actions/upload-artifact@v4
      with:
        name: project_docs
        path: holdem/doc/report/ece499rpt.pdf
        # include-hidden-files: false by default
        if-no-files-found: error
        overwrite: true
        compression-level: 9
        retention-days: 8
