name: Generate holdemdb.zip

on:
  workflow_dispatch:

# [!NOTE]
# If the `sh n_threads_minus_1.sh 3` assertion fails, you'll want to choose a different parallelization/striping strategy to match the number of cores available
# ↓
# 2 3
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15
# etc.
jobs:
  rotation123:
    name: 'make db → bin/regenerate_opening_book (front rotation)'
    runs-on: 'ubuntu-24.04'
    # timeout-minutes: 360
    steps:
    - uses: actions/checkout@v5
    - name: "Build bin/regenerate_opening_book"
      run: |
        sh n_threads_minus_1.sh 3 || exit 78 # EX_CONFIG
        cd holdem && make db
        mkdir -vp /tmp/opening_book
    - name: "Build bin/regenerate_opening_book"
      env:
        HOLDEMDB_PATH: /tmp/opening_book
      run: echo 16 17 18 | tr ' ' "\n" | xargs -P 3 -n 1 bin/regenerate_opening_book

    - name: Upload opening book zip
      uses: actions/upload-artifact@v4
      with:
        name: opening_book-1of2
        path: /tmp/opening_book
        # include-hidden-files: false by default
        if-no-files-found: error
        overwrite: true
        compression-level: 0
        retention-days: 21

  rotation456:
    name: 'make db → bin/regenerate_opening_book (back rotation)'
    runs-on: 'ubuntu-24.04'
    steps:
    - uses: actions/checkout@v5
    - name: "Build bin/regenerate_opening_book"
      run: |
        sh n_threads_minus_1.sh 3 || exit 78 # EX_CONFIG
        cd holdem && make db
        mkdir -vp /tmp/opening_book
    - name: "Build bin/regenerate_opening_book"
      env:
        HOLDEMDB_PATH: /tmp/opening_book
      run: echo 19 20 21 | tr ' ' "\n" | xargs -P 3 -n 1 bin/regenerate_opening_book

    - name: Upload opening book zip
      uses: actions/upload-artifact@v4
      with:
        name: opening_book-2of2
        path: /tmp/opening_book
        if-no-files-found: error
        overwrite: true
        compression-level: 0
        retention-days: 21
