name: Generate holdemdb.zip

on:
  workflow_dispatch:

# [!NOTE]
# If the `sh n_threads_minus_1.sh 3` assertion fails, you'll want to choose a different parallelization/striping strategy to match the number of cores available
# ↓
# 2 3 (2 threads)
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15
# 16 17 18 19 20 21 (6 threads)
# 22 23 24 25 26 27 28
# 29 30 31 32 33 34 35 36
# 37 38 39 40 41 42 43 44 45 (9 threads)
# 46 47 48 49 50 51 52 53 54 55
# 56 57 58 59 60 61 62 63 64 65 66
# 67 68 69 70 71 72 73 74 75 76 77 78 (12 threads)
# etc.
jobs:
  rotation123:
    name: '(front rotation) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    # timeout-minutes: 360
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "16 17 18"
          rotation_suffix: 1of2
        id: generate123

  rotation456:
    name: '(back rotation) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "19 20 21"
          rotation_suffix: 2of2
        id: generate456
