name: Generate holdemdb.zip

on:
  workflow_dispatch:

# [!NOTE]
# If the `sh n_threads_minus_1.sh 3` assertion fails, you'll want to choose a different parallelization/striping strategy to match the number of cores available
# ↓
# 2 3 (2 threads)
# 4 5 6
# 7 8 9 10
# 11 12 13 14 15
# 16 17 18 19 20 21 (6 threads)
# 22 23 24 25 26 27  28
# 29 30 31 32 33 34  35 36
# 37 38 39 40 41 42  43 44 45 (9 threads)
# 46 47 48 49 50 51  52 53 54  55
# 56 57 58 59 60 61  62 63 64  65  66
# 67 68 69 70 71 72  73 74 75  76  77  78 (12 threads)
# 79 80 81 82 83 84  85 86 87  88  89  90  91
# 92 93 94 95 96 97  98 99 100 101 102 103 104 105
# 106 107 108  109 110 111  112 113 114  115 116 117  118 119 120 (15 threads)
# 121 122 123  124 125 126  127 128 129  130 131 132  133 134 135  136
# 137 138 139  140 141 142  143 144 145  146 147 148  149 150 151  152 153
# 154 155 156  157 158 159  160 161 162  163 164 165  166 167 168  169 170 171 (18 threads)
# 172 173 174  175 176 177  178 179 180  181 182 183  184 185 186  187 188 189  190
# 191 192 193  194 195 196  197 198 199  200 201 202  203 204 205  206 207 208  209 210
# 211  etc.
jobs:
  rotation123:
    name: '(mastodon) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    # timeout-minutes: 360
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "211 212 213"
          rotation_suffix: 1of7

  rotation456:
    name: '(pterodactyl) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "214 215 216"
          rotation_suffix: 2of7

  rotation789:
    name: '(triceratops) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "217 218 219"
          rotation_suffix: 3of7

  rotation10_11_12:
    name: '(sabertooth tiger) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "220 221 222"
          rotation_suffix: 4of7

  rotation13_14_15:
    name: '(tyrannosaurus) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "223 224 225"
          rotation_suffix: 5of7

  rotation16_17_18:
    name: '(dragonzord) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "226 227 228"
          rotation_suffix: 6of7

  rotation19_20_21:
    name: '(titanus) make db → bin/regenerate_opening_book'
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/generate_db_one_stripe
        with:
          cpu_threads_expected: 3
          regenerate_opening_book_modes: "229 230 231"
          rotation_suffix: 7of7

  # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-requiring-successful-dependent-jobs
  combine_and_upload_results:
    name: "Aggregate & save for upload"
    runs-on: 'ubuntu-24.04'
    needs: [rotation123, rotation456, rotation789, rotation10_11_12, rotation13_14_15, rotation16_17_18, rotation19_20_21]
    # https://docs.github.com/en/actions/tutorials/store-and-share-data#downloading-artifacts-during-a-workflow-run
    steps:
      - name: Fetch
        uses: actions/download-artifact@v5
        with:
          path: holdemgen.${{ endsWith(github.ref_name, '/merge') && github.head_ref || github.ref_name }}_${{ github.sha }}
          pattern: opening_book-*
          merge-multiple: true
      - name: "Inspect results (supposedly actions/download-artifact will extract the contents for us into $GITHUB_WORKSPACE by default)"
        run: pwd -P && ls -l && cd holdemgen* && ls -l && ls -l */ && cd * && ls -1 *.holdemC *.holdemW | sort | xargs -I @ sh -c 'echo @ start ↓ && hexdump -C @ && echo @ end ↑' > hexdump.txt
      - name: "Done!"
        uses: actions/upload-artifact@v4
        with:
          # https://docs.github.com/en/actions/reference/workflows-and-actions/variables
          # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax
          # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
          name: opening_book-${{ github.run_id }}.${{ endsWith(github.ref_name, '/merge') && github.head_ref || github.ref_name }}_${{github.sha}}-${{ runner.os }}-${{ runner.arch }}
          path: |
            holdemgen*/**/*.holdemC
            holdemgen*/**/*.holdemW
          # include-hidden-files: false by default
          if-no-files-found: error
          overwrite: true
          compression-level: 9
          retention-days: 21
      # The hexdump.txt generated by the "Inspect results" step above is ~18MiB uncompressed
      # It's still about ~7.5MiB zipped. With xz we can get it down to an incremental ~2MiB, which is important because the free tier of Github Actions has only 500 MiB concurrent storage.
      - name: "Compress debugging info"
        run: mkdir -v -p "/tmp/hexdump_and_json-${RUNNER_OS}" && cd holdemgen* && rm -v */*.holdemC */*.holdemW && tar -cv ../holdemgen* | xz -vv -z -9 -e > "/tmp/hexdump_and_json-${RUNNER_OS}/${GITHUB_RUN_ID}.$(hostname)-${RUNNER_ARCH}.tar.xz"
      - name: "Save diagnostics"
        uses: actions/upload-artifact@v4
        with:
          name: inspect_hexdump_and_json-${{ github.run_id }}.${{ endsWith(github.ref_name, '/merge') && github.head_ref || github.ref_name }}_${{github.sha}}-${{ runner.os }}-${{ runner.arch }}
          path: |
            /tmp/hexdump_and_json-*
          include-hidden-files: true
          if-no-files-found: error
          overwrite: true
          compression-level: 9
          retention-days: 8
